[package]
name = "sqlness"
version = "0.1.0"
edition = "2021"
authors = ["Ruihang Xia <waynestxia@gmail.com"]

[dependencies]
async-trait = "0.1.58"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.21", features = ["full"] }
toml = "0.5.9"
walkdir = "2.3"
